//
//  FunData.swift
//  BudBuddy
//
//  Created by Matteo Cola on 07.09.2025.
//

import SwiftUI

let funFacts: [String] = [
    "This application Was crEatED by a high developer, and everytime he worked on it he was fried😂",
    "The developer once tried to debug this app for 2 hours before realizing he was looking at the wrong file. Classic.",
    "If you find a typo, that's not a bug—it's a limited edition feature, handCrafted while vibing.",
    "Testing this app involved snacks, giggles, and a suspicious amount of staring into space.",
    "At least three ideas for this app were lost to the munchies and never recovered.",
    "No actual cannabis leaves were harmed in the making of these floating backGrounds.",
    "The developer's playlist was 90% lo-fi beats and 10% 'forgot what song this is.'",
    "Every time you tap 'HIT ME,' a developer someWhere takes a snack break.",
    "This app was optimized while the dev was searching for his lighter. Priorities.",
    "Some of these suggestions were inspired by the developer's own questionable decisions.",
    "The 'Recent Suggestions' list is like a memory—sometimes short, sometimes really short.",
    "If you stare at the floating leaves long enough, you might achieve enlightenment. Or just zone out.",
    "The existential questions are not responsible for any sudden life epiphanies.",
    "Rumor has it, the more you use this app, the funnier it gets. Or maybe you just get hungrier.",
    "The developer tried to make a 'serious mode.' It lasted 12 minutes.",
    "Every bug fixed in this app was rewarded with a celebratory snack.",
    "No, yOu cAn't rOll the scrEen, but yOu can scrOll it.",
    "This app pairs well with chill vibes and good company.",
    "The developer's favorite strain? Whichever one helped finish this code.",
    "Does somebody actually reads this?",
    "A special thanks to chatGPT for existing.",
    "I dont even what to type at this point, imma ask chatgpt for sum ahhhaha",
    "Imagine this app becomes famous and i become rich somehow"
]
let existentialQuestions: [String] = [
    "What if the people you love are just memories?",
    "Could we already be dead and not know it?",
    "Is the universe indifferent to our existence?",
    "What if reality is just a simulation?",
    "Are our choices truly our own?",
    "Is time an endless loop?",
    "What happens when consciousness fades?",
    "If you forget a dream, did it really happen?",
    "Does the universe notice when you are sad?",
    "Will the heat death of the universe erase all meaning?",
    "If everyone disappeared, would the world still exist?",
    "Are we all just stories told by someone else?",
    "What if your memories are borrowed from another life?",
    "Is free will just an illusion created by the brain?",
    "Do we ever truly know ourselves?",
    "Can anything ever be truly permanent?",
    "What if every decision creates a new universe?",
    "Does the universe have a purpose or is it just chaos?",
    "Are we destined to repeat the same mistakes forever?",
    "Is consciousness just a byproduct of biology?",
    "How do you know anyone else is real?",
    "Will there ever be a final thought?",
    "What if happiness is just a chemical trick?",
    "Do we invent meaning, or discover it?",
    "Is it possible to truly escape loneliness?",
    "If you could live forever, would you want to?",
    "What if the future is already written?",
    "Are your memories accurate, or just convenient stories?",
    "Does the universe end when you die?",
    "Is there a limit to human understanding?",
    "What if every moment has already happened before?",
    "Are we just patterns in the dust of stars?",
    "Is suffering necessary for existence?",
    "Could reality vanish the moment you look away?",
    "What if your entire life is just a fleeting thought?",
    "Would you notice if you were dreaming right now?",
    "Can you ever truly know what others feel?",
    "Is there such a thing as true randomness?",
    "Are you the same person you were yesterday?",
    "What if the universe is just one of many?",
    "Does anything really matter in the end?",
    "Is love just a survival mechanism?",
    "What if you are the only conscious being?",
    "Do your actions echo beyond your life?",
    "Is reality stranger than we can ever imagine?",
    "Are we moving toward something, or just drifting?",
    "What if you could see all your possible lives?",
    "Does silence have a sound?",
    "What is left when nothing is left?",
    "If you could ask one question of the universe, what would it be?"
]
