//
//  MovieSuggestionData.swift
//  BudBuddy
//
//  Created by Matteo Cola on 07.09.2025.
//

import Foundation

struct MovieSuggestion: Identifiable {
    let id = UUID()
    let title: String
    let genre: String
    let description: String
}

let movieSuggestions: [MovieSuggestion] = [
    MovieSuggestion(title: "Inception", genre: "Sci-Fi", description: "Mind-bending visuals and dream layers."),
    MovieSuggestion(title: "The Big Lebowski", genre: "Comedy", description: "Hilarious and perfectly laid-back vibes."),
    MovieSuggestion(title: "Pineapple Express", genre: "Comedy", description: "A classic stoner comedy with wild antics."),
    MovieSuggestion(title: "Fear and Loathing in Las Vegas", genre: "Trippy", description: "Psychedelic visuals and surreal storytelling."),
    MovieSuggestion(title: "Interstellar", genre: "Sci-Fi", description: "Epic space adventure with stunning visuals."),
    MovieSuggestion(title: "Scott Pilgrim vs. The World", genre: "Comedy", description: "Comic book action and quirky humor."),
    MovieSuggestion(title: "Fantastic Planet", genre: "Animated", description: "Surreal, colorful alien world and trippy animation."),
    MovieSuggestion(title: "Enter the Void", genre: "Trippy", description: "Hypnotic visuals and a unique first-person perspective."),
    MovieSuggestion(title: "Dazed and Confused", genre: "Comedy", description: "Classic coming-of-age stoner movie set in the '70s."),
    MovieSuggestion(title: "2001: A Space Odyssey", genre: "Sci-Fi", description: "Iconic visuals and a mind-expanding journey through space."),
    MovieSuggestion(title: "Spirited Away", genre: "Animated", description: "Enchanting visuals and magical world-building."),
    MovieSuggestion(title: "The Grand Budapest Hotel", genre: "Comedy", description: "Wes Anderson’s whimsical style and colorful sets."),
    MovieSuggestion(title: "Waking Life", genre: "Trippy", description: "Philosophical rotoscope animation with dreamlike sequences."),
    MovieSuggestion(title: "Superbad", genre: "Comedy", description: "Hilarious teen misadventures and awkward moments."),
    MovieSuggestion(title: "Howl's Moving Castle", genre: "Animated", description: "Beautiful animation and imaginative story."),
    MovieSuggestion(title: "Harold & Kumar Go to White Castle", genre: "Comedy", description: "Ridiculous adventures and munchies quest."),
    MovieSuggestion(title: "Across the Universe", genre: "Musical", description: "Beatles music and psychedelic visuals."),
    MovieSuggestion(title: "The Matrix", genre: "Sci-Fi", description: "Reality-bending action and philosophical themes."),
    MovieSuggestion(title: "Yellow Submarine", genre: "Animated", description: "Psychedelic Beatles animation and music."),
    MovieSuggestion(title: "Monty Python and the Holy Grail", genre: "Comedy", description: "Absurdist British humor and memorable quotes."),
    MovieSuggestion(title: "Donnie Darko", genre: "Trippy", description: "Mind-bending plot and surreal atmosphere."),
    MovieSuggestion(title: "Avatar", genre: "Sci-Fi", description: "Lush alien world and vibrant visuals."),
    MovieSuggestion(title: "Half Baked", genre: "Comedy", description: "Goofy stoner humor and crazy schemes."),
    MovieSuggestion(title: "Cloud Atlas", genre: "Sci-Fi", description: "Sprawling, interconnected stories across time."),
    MovieSuggestion(title: "Adventure Time: Distant Lands", genre: "Animated", description: "Colorful, imaginative, and delightfully weird."),
    MovieSuggestion(title: "Kung Fu Hustle", genre: "Comedy", description: "Over-the-top martial arts and cartoonish action."),
    MovieSuggestion(title: "Doctor Strange", genre: "Sci-Fi", description: "Reality-warping magic and dazzling effects."),
    MovieSuggestion(title: "The Trip", genre: "Trippy", description: "1960s psychedelic journey and visuals."),
    MovieSuggestion(title: "Shrek", genre: "Animated", description: "Quirky humor and fun for all ages."),
    MovieSuggestion(title: "Tenacious D in The Pick of Destiny", genre: "Comedy", description: "Rock and roll antics and stoner humor."),
    MovieSuggestion(title: "Paprika", genre: "Animated", description: "Dreamlike anime with mind-bending visuals."),
    MovieSuggestion(title: "Beetlejuice", genre: "Comedy", description: "Spooky fun and Tim Burton’s quirky style."),
    MovieSuggestion(title: "The Science of Sleep", genre: "Trippy", description: "Surreal dream sequences and creative visuals."),
    MovieSuggestion(title: "Guardians of the Galaxy", genre: "Sci-Fi", description: "Space adventure, great music, and laughs."),
    MovieSuggestion(title: "Zombieland", genre: "Comedy", description: "Hilarious zombie apocalypse with wild action."),
    MovieSuggestion(title: "Coraline", genre: "Animated", description: "Creepy, colorful stop-motion adventure."),
    MovieSuggestion(title: "The Mask", genre: "Comedy", description: "Wild cartoonish antics and Jim Carrey’s energy."),
    MovieSuggestion(title: "Akira", genre: "Animated", description: "Groundbreaking anime with intense visuals."),
    MovieSuggestion(title: "Bill & Ted's Excellent Adventure", genre: "Comedy", description: "Time-traveling fun and goofy humor."),
    MovieSuggestion(title: "Labyrinth", genre: "Fantasy", description: "Fantastical creatures and musical numbers."),
    MovieSuggestion(title: "The Fifth Element", genre: "Sci-Fi", description: "Colorful, over-the-top sci-fi spectacle."),
    MovieSuggestion(title: "Hot Fuzz", genre: "Comedy", description: "Clever parody and rapid-fire jokes."),
    MovieSuggestion(title: "The Lego Movie", genre: "Animated", description: "Playful visuals and clever comedy."),
    MovieSuggestion(title: "The Holy Mountain", genre: "Trippy", description: "Surreal, symbolic, and visually intense."),
    MovieSuggestion(title: "Spaceballs", genre: "Comedy", description: "Hilarious sci-fi parody and slapstick."),
    MovieSuggestion(title: "Fantastic Mr. Fox", genre: "Animated", description: "Stop-motion whimsy and clever dialogue."),
    MovieSuggestion(title: "Alice in Wonderland", genre: "Fantasy", description: "Classic trippy adventure in a magical world."),
    MovieSuggestion(title: "The Rocky Horror Picture Show", genre: "Musical", description: "Cult classic with wild costumes and songs."),
    MovieSuggestion(title: "Who Framed Roger Rabbit", genre: "Animated", description: "Animated/live-action mashup and zany fun."),
    MovieSuggestion(title: "Tropic Thunder", genre: "Comedy", description: "Over-the-top satire and absurd humor."),
    MovieSuggestion(title: "Baraka", genre: "Trippy", description: "Stunning global visuals and hypnotic soundtrack."),
    MovieSuggestion(title: "Wallace & Gromit: The Wrong Trousers", genre: "Animated", description: "Charming British claymation adventure."),
    MovieSuggestion(title: "Shaun of the Dead", genre: "Comedy", description: "Zombie comedy with witty British humor."),
    MovieSuggestion(title: "Willy Wonka & the Chocolate Factory", genre: "Fantasy", description: "Colorful sets and whimsical imagination."),
    MovieSuggestion(title: "The Secret Life of Walter Mitty", genre: "Adventure", description: "Dreamy visuals and inspiring journey."),
    MovieSuggestion(title: "The Animatrix", genre: "Animated", description: "Anthology of trippy, mind-bending stories."),
    MovieSuggestion(title: "Sausage Party", genre: "Animated", description: "Raunchy animated comedy with wild scenarios."),
    MovieSuggestion(title: "Rubin and Ed", genre: "Comedy", description: "Absurd road trip and offbeat humor."),
    MovieSuggestion(title: "Brazil", genre: "Trippy", description: "Surreal dystopian satire and imaginative sets."),
    MovieSuggestion(title: "Beavis and Butt-Head Do America", genre: "Animated", description: "Ridiculous antics and dumb humor."),
    MovieSuggestion(title: "Napoleon Dynamite", genre: "Comedy", description: "Quirky characters and deadpan laughs."),
    MovieSuggestion(title: "The Cat Returns", genre: "Animated", description: "Magical adventure with whimsical cats."),
    MovieSuggestion(title: "The Truman Show", genre: "Comedy", description: "Satirical take on reality and perception."),
    MovieSuggestion(title: "The Adventures of Baron Munchausen", genre: "Fantasy", description: "Imaginative, over-the-top storytelling."),
    MovieSuggestion(title: "Men in Black", genre: "Sci-Fi", description: "Alien comedy with cool gadgets and jokes."),
    MovieSuggestion(title: "Kubo and the Two Strings", genre: "Animated", description: "Beautiful stop-motion fantasy adventure."),
    MovieSuggestion(title: "Step Brothers", genre: "Comedy", description: "Outrageous sibling rivalry and silly moments."),
    MovieSuggestion(title: "The Fall", genre: "Trippy", description: "Visually stunning fantasy epic."),
    MovieSuggestion(title: "Soul", genre: "Animated", description: "Philosophical Pixar story with jazzy vibes."),
    MovieSuggestion(title: "This Is the End", genre: "Comedy", description: "Celebrity apocalypse with absurd humor."),
    MovieSuggestion(title: "The Congress", genre: "Trippy", description: "Live-action/animated blend with surreal twists."),
    MovieSuggestion(title: "The Hitchhiker's Guide to the Galaxy", genre: "Sci-Fi", description: "Absurd space adventure and British wit."),
    MovieSuggestion(title: "Mandy", genre: "Trippy", description: "Psychedelic horror with intense visuals."),
    MovieSuggestion(title: "Rango", genre: "Animated", description: "Quirky desert adventure with surreal humor."),
    MovieSuggestion(title: "Clueless", genre: "Comedy", description: "Iconic '90s comedy with fun fashion."),
    MovieSuggestion(title: "The Little Prince", genre: "Animated", description: "Imaginative animation and heartfelt story."),
    MovieSuggestion(title: "Rubber", genre: "Trippy", description: "Absurdist horror-comedy about a killer tire."),
    MovieSuggestion(title: "Team America: World Police", genre: "Comedy", description: "Puppet mayhem and outrageous satire."),
    MovieSuggestion(title: "Ghost in the Shell", genre: "Animated", description: "Philosophical cyberpunk anime."),
    MovieSuggestion(title: "The Life Aquatic with Steve Zissou", genre: "Comedy", description: "Whimsical sea adventure and dry humor."),
    MovieSuggestion(title: "The SpongeBob SquarePants Movie", genre: "Animated", description: "Underwater silliness and colorful gags."),
    MovieSuggestion(title: "The NeverEnding Story", genre: "Fantasy", description: "Imaginative creatures and magical worlds."),
    MovieSuggestion(title: "The Room", genre: "Comedy", description: "So-bad-it’s-good cult classic."),
    MovieSuggestion(title: "The Secret of Kells", genre: "Animated", description: "Celtic-inspired, lush animation."),
    MovieSuggestion(title: "Trolls", genre: "Animated", description: "Vibrant colors and musical fun."),
    MovieSuggestion(title: "The Blues Brothers", genre: "Comedy", description: "Musical comedy with wild car chases."),
    MovieSuggestion(title: "The Love Witch", genre: "Trippy", description: "Retro visuals and campy horror vibes."),
    MovieSuggestion(title: "Heavy Metal", genre: "Animated", description: "Psychedelic sci-fi fantasy anthology."),
    MovieSuggestion(title: "Pulp Fiction", genre: "Comedy", description: "Stylish, quotable, and nonlinear storytelling."),
    MovieSuggestion(title: "The Lorax", genre: "Animated", description: "Colorful Dr. Seuss adaptation with a message."),
    MovieSuggestion(title: "Kung Pow! Enter the Fist", genre: "Comedy", description: "Martial arts parody with absurd humor."),
    MovieSuggestion(title: "Moonrise Kingdom", genre: "Comedy", description: "Whimsical coming-of-age adventure."),
    MovieSuggestion(title: "Speed Racer", genre: "Trippy", description: "Hyper-colorful racing action and visuals."),
    MovieSuggestion(title: "Inside Out", genre: "Animated", description: "Creative look at emotions and memories."),
    MovieSuggestion(title: "Wayne's World", genre: "Comedy", description: "Rocking laughs and pop culture references."),
    MovieSuggestion(title: "The Secret Life of Pets", genre: "Animated", description: "Cute animal antics and slapstick humor."),
    MovieSuggestion(title: "Eternal Sunshine of the Spotless Mind", genre: "Trippy", description: "Surreal love story and memory play."),
    MovieSuggestion(title: "Guardians of the Galaxy Vol. 2", genre: "Sci-Fi", description: "Colorful cosmic adventure and laughs."),
    MovieSuggestion(title: "Soul Plane", genre: "Comedy", description: "Over-the-top airplane comedy."),
    MovieSuggestion(title: "Ratatouille", genre: "Animated", description: "Charming rat chef and Parisian vibes."),
    MovieSuggestion(title: "The Boondock Saints", genre: "Comedy", description: "Dark humor and stylized action."),
    MovieSuggestion(title: "Spider-Man: Into the Spider-Verse", genre: "Animated", description: "Stunning comic book visuals and story."),
    MovieSuggestion(title: "Napoleon Dynamite", genre: "Comedy", description: "Awkward, quirky, and endlessly quotable."),
]
